### ISSUE TITLE
Suggestion: station info

### ISSUE THREAD

**Issue by drmrbrewer** [aeharding/metar-taf-parser#58]
It would be neat if the parser could decode e.g. `CYVR` to `Vancouver International Airport` (i.e. provide details of the station), which it doesn't seem to at present... need to get that from other information in the raw feed (if available), or look it up separately.

**Comment by aeharding** [comment]
Unfortunately, this data is ever-changing and also quite a large dataset. There might be other projects that provide the JSON for you to do the lookup, or perhaps that information is included alongside the METAR/TAF (for example, aviationweather.gov which also provides coordinates and altitude). Because of that, it's out of scope for this project.

I'm going to close this issue, but feel free to open a discussion in the "discussions" tab because it's definitely relevant to how people use this library.

**Comment by drmrbrewer** [comment]
OK, fair enough!
