### ISSUE TITLE
Suggestion: consistent treatment of units

### ISSUE THREAD

**Issue by drmrbrewer** [aeharding/metar-taf-parser#59]
Is there a way to ask the parser *not* to convert altitude from InHg to hPa?  I'm not particularly fussed about this, but seeing as though there is no unit conversion for other values (like wind speed `KT`, temperature `°C` and visibility `SM`) it would seem more consistent if there were also no unit conversion for altitude... i.e. we either do all the conversion at our side, or all on your side, not a mix of the two. 

In fact, I understand that the altitude value in the raw METAR can either be prefixed with `A` (meaning InHg) or `Q` (meaning hPa)... so I assume that in both cases the library returns a value in hPa?  Would it be more consistent to specify a value and unit for altitude, like is the case for wind speed?

![image](https://user-images.githubusercontent.com/9009792/215531255-703415dc-a037-465c-ab71-99276dadd390.png)

**Comment by aeharding** [comment]
This makes complete sense. I don't think the library should convert units (except to parse human readable to machine readable)... for example, `1 1/4` to `1.25`.

**Comment by drmrbrewer** [comment]
Thanks for considering this.  It would also seem to make sense to present `temperature` and `dewpoint` in a consistent manner to others, with `value` and `unit`?

![image](https://user-images.githubusercontent.com/9009792/215537589-cb1840f0-0bae-46e7-b128-de3299c847f3.png)

Incidentally what source for METAR/TAF do you use?  I have been using [NOAA](https://www.aviationweather.gov/adds/dataserver/) but it isn't the most reliable, and seems somewhat dated.  More recently I've come across [this source](https://www.checkwxapi.com/) which seems pretty good.

**Comment by aeharding** [comment]
Changing temperature/dewPoint to objects to accomodate `raw` is a possibility, although providing `unit` is unnecessary for those because temps are always degC afaik. Ideally I'd only provide `unit` if the unit of measurement is dynamic.

As for data sources, aviationweather.gov works fine (also note there's beta.aviationweather.gov e.g. https://beta.aviationweather.gov/cgi-bin/data/metar.php?ids=KORD&format=json with an updated JSON api, although it parses the report which is unecessary overhead if you're already using metar-taf-parser).

You can also query directly from the source e.g. https://tgftp.nws.noaa.gov/data/forecasts/taf/stations/KMSN.TXT but that doesn't have airport metadata available (coordinates, elevation etc). That's what the example site uses.

**Comment by drmrbrewer** [comment]
> although providing unit is unnecessary for those because temps are always degC afaik.

I think that may be the case, though I don't know the METAR rules in sufficient detail to know if there might be a modifier (like there is for altitude: `A` or `Q`) for those locations that more routinely deal in Fahrenheit.  Probably not, but including the unit anyway would be a belt and braces approach.
