### ISSUE TITLE
Rounding error in altitude conversion?

### ISSUE THREAD

**Issue by drmrbrewer** [aeharding/metar-taf-parser#61]
Shouldn't `3049 InHg` convert to `1033 hPa` rather than `1032 hPa` in [this example](https://aeharding.github.io/metar-taf-parser/metar?input=CYVR+301300Z+09006KT+15SM+FEW055+FEW120+M04%2FM06+A3049+RMK+SC1AC1+SC+TR+SLP327)?  It converts to `1032.51` with greater precision.

**Comment by clioh** [comment]
Would love to have the option of returning in inches of mercury as well

**Comment by aeharding** [comment]
@clioh that actually will be addressed with https://github.com/aeharding/metar-taf-parser/issues/59. metar-taf-parser will return the value in the unit provided on the metar (InHg or hPA depending). And then the user can convert themselves, if that's wanted. :)

@drmrbrewer assuming that this will be handled in #59, it should make this conversion bug irrelevant (since there will be no conversion). So I am going to close this bug.
